---
output:
  pdf_document: default
  html_document: default
---
 -  -  - 
title: "Chapter 8 Labs from ISLR"
output:
 html_document:
 df_print: paged
 -  -  - 


Chapter 8 Lab: Decision Trees

Fitting Classification Trees

```{r}
library(tree)
library(ISLR)
attach(Carseats)
High = ifelse(Sales <= 8, "No", "Yes")
Carseats = data.frame(Carseats, High)
tree.carseats = tree(High ~ .  -  Sales, Carseats)
summary(tree.carseats)
```

```{r}
plot(tree.carseats)
text(tree.carseats, pretty = 0)
```

```{r}
tree.carseats
```

```{r}
set.seed(2)
train = sample(1:nrow(Carseats), 200)
Carseats.test = Carseats[ - train, ]
High.test = High[ - train]
tree.carseats = tree(High ~ . - Sales, Carseats, subset = train)
tree.pred = predict(tree.carseats, Carseats.test, type = "class")
#These lines below redesigned by me because the hardcoded values, (86 + 57)/200, were no longer relevant.
my_tree  =  table(tree.pred, High.test)
my_tree
(my_tree[1, 1] + my_tree[2, 2]) / sum(my_tree)
```

```{r}
set.seed(3)
cv.carseats = cv.tree(tree.carseats, FUN = prune.misclass)
names(cv.carseats)
cv.carseats
```

```{r}
par(mfrow = c(1, 2))
plot(cv.carseats$size, cv.carseats$dev, type = "b")
plot(cv.carseats$k, cv.carseats$dev, type = "b")
```

```{r}
prune.carseats = prune.misclass(tree.carseats, best = 9)
plot(prune.carseats)
text(prune.carseats, pretty = 0)
```

```{r}
tree.pred = predict(prune.carseats, Carseats.test, type = "class")
# Edited code below to update.  Fixed values, (94 + 60)/200, were incorrect, 
my_tree  =  table(tree.pred, High.test)
my_tree
(my_tree[1, 1] + my_tree[2, 2]) / sum(my_tree)
```

```{r}
prune.carseats = prune.misclass(tree.carseats, best = 15)
plot(prune.carseats)
text(prune.carseats, pretty = 0)
tree.pred = predict(prune.carseats, Carseats.test, type = "class")
# Edited code below to update.  Fixed values, (86 + 62)/200, were incorrect, 
table(tree.pred, High.test)
my_tree  =  table(tree.pred, High.test)
my_tree
(my_tree[1, 1] + my_tree[2, 2]) / sum(my_tree)
```

Fitting Regression Trees

```{r}
library(MASS)
set.seed(1)
train  =  sample(1:nrow(Boston), nrow(Boston)/2)
tree.boston = tree(medv ~ ., Boston, subset = train)
summary(tree.boston)
```

```{r}
plot(tree.boston)
text(tree.boston, pretty = 0)
```

```{r}
cv.boston = cv.tree(tree.boston)
plot(cv.boston$size, cv.boston$dev, type = 'b')
```

```{r}
prune.boston = prune.tree(tree.boston, best = 5)
plot(prune.boston)
text(prune.boston, pretty = 0)
```

```{r}
yhat = predict(tree.boston, newdata = Boston[ - train, ])
boston.test = Boston[ - train, "medv"]
plot(yhat, boston.test)
abline(0, 1)
mean((yhat - boston.test) ^ 2)
```

Bagging and Random Forests

```{r}
library(randomForest)
set.seed(1)
bag.boston = randomForest(medv ~ ., data = Boston, subset = train, mtry = 13, importance = TRUE)
bag.boston
```

```{r}
yhat.bag  =  predict(bag.boston, newdata = Boston[ - train, ])
plot(yhat.bag, boston.test)
abline(0, 1)
mean((yhat.bag - boston.test) ^ 2)
```

```{r}
bag.boston = randomForest(medv ~ ., data = Boston, subset = train, mtry = 13, ntree = 25)
yhat.bag  =  predict(bag.boston, newdata = Boston[ - train, ])
mean((yhat.bag - boston.test) ^ 2)
```

```{r}
set.seed(1)
rf.boston = randomForest(medv ~ ., data = Boston, subset = train, mtry = 6, importance = TRUE)
yhat.rf  =  predict(rf.boston, newdata = Boston[ - train, ])
mean((yhat.rf - boston.test) ^ 2)
```

```{r}
importance(rf.boston)
```

```{r}
varImpPlot(rf.boston)
```

Boosting

```{r}
library(gbm)
set.seed(1)
boost.boston = gbm(medv ~ ., data = Boston[train, ], distribution = "gaussian", n.trees = 5000, interaction.depth = 4)
summary(boost.boston)
```

```{r}
par(mfrow = c(1, 2))
plot(boost.boston, i = "rm")
plot(boost.boston, i = "lstat")
```

```{r}
yhat.boost = predict(boost.boston, newdata = Boston[ - train, ], n.trees = 5000)
mean((yhat.boost - boston.test) ^ 2)
```

```{r}
boost.boston = gbm(medv ~ ., data = Boston[train, ], distribution = "gaussian", n.trees = 5000, interaction.depth = 4, shrinkage = 0.2, verbose = F)
yhat.boost = predict(boost.boston, newdata = Boston[ - train, ], n.trees = 5000)
mean((yhat.boost - boston.test) ^ 2)
```